### ISSUE TITLE
Temporary extract directory permissions are too restrictive

### ISSUE THREAD

**Issue by haboustak** [JonathonReinhart/staticx#286]
I am trying to use `staticx@0.14.1` with a `pyinstaller@6.9.0 --onefile` binary on Debian 12.5 and I'm receiving the following error:
```
$ sudo ./dist/script
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
  File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
PermissionError: [Errno 13] Permission denied: '/tmp/staticx-FegNEo/script.onefile'
```

My script does a few unusual things that trigger this error.
1. It must be run as `root`
2. It switches the current user in order to access specific system resources (e.g. a database or a filesystem or a device)
3. It lazily imports a Python module from the `onefile` package, such that the module is imported after the user switch.

The permissions on the temporary directory created by `staticx` are `700`, but they should be `755`.
```
$ ls -ald /tmp/staticx-FegNEo/
drwx------ 2 root root 4096 Aug  3 12:05 /tmp/staticx-FegNEo/
```

Minimal reproducing script is below.
```python
import os
import sys

def main():
    if os.geteuid() != 0:
        print("ERROR: You must execute this script as root");
        sys.exit(1)

    # The uid/gid 1000 is the first non-system user on Debian 12
    # assumed to exist for this reproducer
    os.setgid(1000)
    os.setuid(1000)

    # lazy import after user switch triggers PermissionError
    import yaml
    print('ok')

if __name__ == '__main__':
    main()
```

I'm running `staticx` this way:
```yaml
image: registry.gitlab.com/haboustak/glartifacts/build-env:1.3

aliases:
  onefile:
    script:
      - pyinstaller --onefile --distpath ./dist -n script.onefile ./script.py
      - staticx ./dist/script.onefile ./dist/script
 ```
